### ISSUE TITLE
Sprint 2 Review

### ISSUE THREAD

**Issue by RRIOPEL18** [YardSale2020/yard-sale-web-app#17]
@RRIOPEL18 - Contributed to and reviewed the paper prototype and UX in XD. Added all the placeholder code and set up pattern library.

@sander-aaron - Contributed to the paper prototype and built the UX in XD.

@Miriampion - Did a lot of preliminary research, built and designed the paper prototype, contributed to the UX in XD. Also wrote the rubric and reviewed prototype flow. 

ALL - Research document.

@thomasjbradley

**Comment by thomasjbradley** [comment]
More details next time please.
